### ISSUE TITLE
Provide links to buy stickers

### ISSUE THREAD

**Issue by popey** [fundopensource/fundopensource.github.io#3]
The lovely people at [UnixStickers](https://www.unixstickers.com/) provide kickbacks to projects who projects whose logos they sell merch for. Might be nice to allow visitors to fundopensource to be able to get directly to those pages (e.g. [elementary OS](http://www.unixstickers.com/tag/elementaryos) merch page). 

I have no affiliation to UnixStickers, I just know they make nice stickers, and know Canonical get sent loads of stickers as a kickback periodically.

**Comment by popey** [comment]
I guess your current links cover this then :)

**Comment by danrabbit** [comment]
I was just going to ask if that was alright :)
