### ISSUE TITLE
Suggestion box

### ISSUE THREAD

**Issue by tuxayo** [fundopensource/fundopensource.github.io#5]
Here could be the place to dump suggestions about projects or people to add.
I'm not sure if this is appropriate, you tell me ;)

**Comment by tuxayo** [comment]
# Lists
https://liberapay.com/
https://salt.bountysource.com/
https://www.reddit.com/r/linux/comments/5omtvg/patreons_to_support_open_source_projects_please/
https://gratipay.com/
https://opencollective.com/opensource


# Individual projects/people

### FNA dev Ethan Lee
https://www.patreon.com/flibitijibibo

### Jonathan Thomas – OpenShot dev
https://www.patreon.com/openshot

### Pulse Audio maintainer
https://www.patreon.com/tanuk

### Ryan C. Gordon/Icculus
https://www.patreon.com/icculus

### Mastodon dev + main instance
https://www.patreon.com/mastodon/

### ncase/Nicky Case
https://www.patreon.com/ncase

### GIMP
https://www.gimp.org/donating/

### GIMP/GEGL dev
https://www.patreon.com/pippin

### openStreetMap

### TOR

### torservers
https://www.torservers.net

### Conversations
Contributes to move XMPP forward.
https://conversations.im/#donate

### Eclipse

### F-Droid

### GPG/GNU PG
https://www.gnupg.org/donate/index.html

### Krita Foundation
https://krita.org/en/support-us/donations/

### DAV Droid
https://davdroid.bitfire.at/donate/

### OpenBikeSharing
https://github.com/bparmentier/OpenBikeSharing#donations

### Enigmail

### PlayOnLinux
https://www.playonlinux.com/en/

### Wine

### FSF

### FSF Europe

### Letsencrypt

### EFF
HTTPS Everywhere and Privacy Badger

### Wikimedia/Wikipedia

### Tails

### Secure Drop
https://freedom.press/crowdfunding/securedrop/

### Signal
https://freedom.press/crowdfunding/signal/

### VLC

### GNU Guix

### OsmAnd

### LibreOffice/The Document Foundation

### PyBitmessage
https://www.reddit.com/r/bitmessage/comments/3xpy3h/pybitmessage_donations_address/

### OpenBSD foundation (OpenSSH, LibreSSL, OpenBSD)
http://www.openbsdfoundation.org/donations.html

### KDE

### Qubes OS

### Rob Landley
https://www.patreon.com/landley

### bcachefs
https://www.patreon.com/bcachefs

### Redox OS and TFS
https://www.patreon.com/redox_os
https://github.com/redox-os/tfs
https://www.phoronix.com/scan.php?page=news_item&px=TFS-File-System-Rust-ZFS#

### Pitivi

### PyDev
https://www.patreon.com/fabioz

### Vue.js
https://www.patreon.com/evanyou

### Eric S. Raymond
https://www.patreon.com/esr

It's been a long time I didn't looked at my donation backlog + active donations list and keep appending to it. I hope this can help ^^

**Comment by krytarowski** [comment]
NetBSD

**Comment by danrabbit** [comment]
Please don't dump a bunch of links. Pull requests would be great. Individual issue reports are fine. Mega issue reports are not trackable and unmaintainable.
